### ISSUE TITLE
Error: Can't resolve '@cowprotocol/app-data' in 'my-project/node_modules/@cowprotocol/cow-sdk/dist'

### ISSUE THREAD

**Issue by Adarsh-K** [cowprotocol/cow-sdk#71] opened 2022-08-17 09:34 UTC
I'm using React 18.02 & installed `cow-sdk` using `yarn add @cowprotocol/cow-sdk`. I'm getting the following error:

`Error: Can't resolve '@cowprotocol/app-data' in '/my-project/node_modules/@cowprotocol/cow-sdk/dist'.`

I have `"@cowprotocol/cow-sdk": "^1.0.0-RC.5"` added in my package.json file.

I tried reinstalling cow-sdk, but still getting the same error. What might be the issue?

**Comment by alfetopito** [comment] 2022-08-24 16:18
Hey @Adarsh-K , sorry I missed this!

Anyway, continuing the discussion Anxo was having with you, we are still not able to reproduce. Could you please provide more info, such as the stack trace with the error?

Also, one suspicion is that you might have a stale/cached version of `@cowprotocol/app-data` which had a bug similar to what you describe.
Please try to clean your `node_modules` and yarn/package.lock and let us know if that fixes the issue.

For reference, I could reproduce with an older version, but not on latest cow-sdk RC release https://github.com/cowprotocol/cow-sdk/issues/74

**Comment by anxolin** [comment] 2023-03-31 19:39
Hi @Adarsh-K , sorry for the big delay in the response. We didn't pay the attention to the SDK it deserves. 

There's now a new 2.0 version, it should be solved now. I will close this issue, feel free to re-open if it's not solved

**Closed by anxolin** 2023-03-31 19:39 UTC
